# image: Visual Studio 2017
version: "{build}"
build: off
skip_tags: true

environment:
  matrix:
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i --ignore-scripts
  - for /f %%i in ('node -v') do set exact_nodejs_version=%%i
  - git submodule update --init --recursive
  - node build %exact_nodejs_version%

on_success:
 - for %%i in (prebuilds\*) do appveyor PushArtifact %%i
